# Generated by Django 3.0.4 on 2020-03-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
